### ISSUE TITLE
`get_mutations_df` returns ambiguously defined `predicted_func_score`

### ISSUE THREAD

**Issue by jbloom** [matsengrp/multidms#110]
The `Model.get_mutations_df` method returns a "predicted_func_score" column, but it is not clear which condition this predicted functional score is for---is it the reference condition? Should predicted functional scores also be returned for non-reference conditions?

**Comment by jgallowa07** [comment]
Good catch - this is a bug. I make predictions for all conditions but they just get over-written to the same column. Fixing now
