### ISSUE TITLE
consistency in output between versions

### ISSUE THREAD

**Issue by jbloom** [matsengrp/multidms#115]
@jgallowa07, now that we are trying to build this into pipelines, I was wondering if you would be able to try to ensure backwards-compatibility between minor versions?

I'm thinking specifically of how version 0.2.1 changed the output of `get_mutations_df` from 0.2.0 to no longer have "mutations" as a column but to make it the index. This change itself is fine, but it broke all our pipelines which thought there was a "mutations" columns and took me a while to troubleshoot while all our pipelines broke.

Would it be possible to try to limit backwards-incompatible changes to just major version changes going forward?

**Comment by jgallowa07** [comment]
My apologies! 

Yes, I think any change to output's input should and will (from now on) have backward compatibility and deprecation in minor revisions prior to major releases. I'll add this to "CONTRIBUTING.rst"
