### ISSUE TITLE
Simulations outline

### ISSUE THREAD

**Issue by jgallowa07** [matsengrp/multidms#125]
Here we're going to describe some of the next steps to validating our model with simulations. We have a working example [here](https://github.com/matsengrp/multidms/blob/main/notebooks/simulate_data.ipynb), however this was just a first pass. The goal of these simulations are two-fold. To validate the model performance as it relates to the spike data, as well as to more broadly explore the landscape of model attributes. In other works, in what scenarios does the model perform well, and where does it break. 

## Things to explore wrt the DMS data:

- number of parameters to infer (e.g. size of protein), 
- number of conditions (i.e. how many sets of shifts are we trying to infer at once)
- how the variant library attributes (number of mutations, number of barcode replicates, amount of noise, bottleneck causing imbalance in variant frequency.)
- differing number and strength of shifts.

## Things to explore wrt Model choice

- linear model vs non-linear
- choice of reference

## Misc.

> (e.g. sequencing depth, differences in enrichment ratios across experiments, or the mutations considered - the data they use include naturally mutations, rather than all possible amino acid mutants, leading to a bias against deleterious mutations)

**Comment by matsen** [comment]
I suggest we start first with the simulation to mimic the spike study as closely as possible as measured using summary statistics. 

Also, I'd want to have some summary that measures something about the amount of "noise"-- but perhaps that's already handled nicely by the dms_variants simulator.
