### ISSUE TITLE
simulation manuscript figures notebook.

### ISSUE THREAD

**Issue by jgallowa07** [matsengrp/multidms#139]
Issue to add the plotting notebook for the manuscript simulation figures.

**Comment by jgallowa07** [comment]
I've started a branch [139_simulation_manuscript_figures](https://github.com/matsengrp/multidms/tree/139_simulation_manuscript_figures) with the main figure. 

Supplementary figures TODO:

- [ ] Simulated shift heatmaps - for default and other parameter sets run through notebook
- [ ] recovery of beta's across sweep (a version of this exists in the simulation notebook already)
- [ ] All scatter plots of shift recovery across lasso sweep
- [ ] 2 more of the panel C figures, but for the other parameter sets

**Comment by jgallowa07** [comment]
@Haddox I think you have mostly finished these tasks? Can you push the notebook and PR so we can get this closed?

**Comment by Haddox** [comment]
@jgallowa07: will do! Right now it uses an absolute path for `datadir`, e.g.:

```
simdir = 'beta_ridge_1e-7'
datadir = os.path.join('/fh/fast/matsen_e/shared/multidms/2024-02-28-simulations-output', simdir)
```

What is the relative path that I should use instead?

**Comment by jgallowa07** [comment]
We've decided to move this code to the [manuscript analysis repo](https://github.com/matsengrp/SARS-CoV-2_spike_multidms). closing.
