### ISSUE TITLE
Single-precision optimization

### ISSUE THREAD

**Issue by WSDeWitt** [matsengrp/multidms#150]
This commented-out line suggests we are doing single-precision optimization, which may not be enough for good convergence behavior. It might be worth checking if the output parameters of the jaxopt calls are jax arrays of doubles, and if not, assess if using double precision improves convergence issues.

https://github.com/matsengrp/multidms/blob/79dc61a989387b6a070be9e8f65afc24b1903c08/multidms/biophysical.py#L41

**Comment by jgallowa07** [comment]
Thanks, @WSDeWitt IIRC I saw no tangible difference, for instance, between the manuscript results from the first submission (double precision), and this iteration or results which is indeed float32 single precision. 

That said, I could have missed something without good error-through-iterations data - this should be done with the new convergence functionality that I'm working on now over in #149

**Comment by jgallowa07** [comment]
This has been addressed in #151 - Let's close this when that get's merged.
