### ISSUE TITLE
is it necessary to pin `altair` to 5.1.2 rather than just say >=5.1.2?

### ISSUE THREAD

**Issue by jbloom** [matsengrp/multidms#165]
Right now `multidms` version 0.4.0 (and in fact all the versions, but `multidms` 0.4.0 is most relevant to me) are pinning `altair` at version 5.1.2 (see [here](https://github.com/matsengrp/multidms/blob/0.4.0/pyproject.toml#L45)).

@jgallowa07 @Haddox, could you cut a version 0.4.1 that just makes it `altair>=5.1.2` or something like that? At this point `altair` is on version 5.5.0, so this means any environment using `multidms` has to use a fairly outdated version.

Anyway, if this is feasible to do it would help us out a lot to have a version like that available to use immediately.

Also, I would advocate as much as possible for putting minimum versions rather than specific pins on the versions unless there is a good reason otherwise.

**Comment by jgallowa07** [comment]
@jbloom [0.4.2](https://github.com/matsengrp/multidms/releases/tag/0.4.2) has been released. Closing this, and opening a new issue to incorporate these dependencies moving forward.
