### ISSUE TITLE
Suggestions for cleaning up in prep for submission

### ISSUE THREAD

**Issue by matsen** [matsengrp/multidms#69]
A couple of things:

* [x] The `README.md` in the notebooks directory mentions ermine-- let's clear that out. Are all of the notebooks still relevant there?
* [x] The tests in `tests` are pretty trivial compared to the complexity of the code. There is some cruft there. Perhaps just clear them out? 
* [x] There are some references to "manuscript X" etc-- let's fix those once the title gets finalized.
* [x] We should link to <https://github.com/matsengrp/SARS-CoV-2_spike_multidms>
* [x] The README in that repo could use some revision
* [ ] The manuscript describes a Docker container on quay, but I see no Dockerfile in either repo, nor do I see a container on <https://quay.io/organization/matsengrp>
* [x] Grep for TODOs
* [x] The notebook uses the "conditions" terminology which has changed in the manuscript. We don't necessarily have to do a global replace, but there should at least be a translation table.
* [x] Is the package actually on PyPI? If so, link in README please, and it seems like we should have pip install from PyPI instructions.

**Comment by jgallowa07** [comment]
A global replace of "condition" -> "experiment" is certainly possible, and probably best to do sooner rather than later if so. Is this something we want to do? @jbloom @matsen @WSDeWitt
