### ISSUE TITLE
some sort continuous integration testing?

### ISSUE THREAD

**Issue by jbloom** [matsengrp/multidms#70]
I think it would be a good idea to have at least some sort of testing run on the code. Right now as far as I can tell there are no CI tests, right?

**Comment by jgallowa07** [comment]
Just as an update, this is what we have so far for unit tests. I'll be sure to add a gh action for CI soon. It's not perfect but I believe it has pretty good coverage - please let me know if you have suggestions.

**Comment by jgallowa07** [comment]
We now have CI testing:

- [pytest unit tests](https://github.com/matsengrp/multidms/blob/ada8cda3847543ee3b0a5d5acf06927eae9bd06b/.github/workflows/build_test_package.yml#L49)
- [Ruff Linting](https://github.com/matsengrp/multidms/blob/ada8cda3847543ee3b0a5d5acf06927eae9bd06b/.github/workflows/build_test_package.yml#L27)
- [Black Formatting](https://github.com/matsengrp/multidms/blob/ada8cda3847543ee3b0a5d5acf06927eae9bd06b/.github/workflows/build_test_package.yml#L30)

Additionally, upon release this action will publish to PyPI (I'll be cutting a `0.9.0` today, probably)
