### ISSUE TITLE
ability to predict phenotypes (functional scores) of variants

### ISSUE THREAD

**Issue by jbloom** [matsengrp/multidms#71]
Right now there is no method for predicting the functional scores in each condition of any variants outside the training set. I think adding such functionality is important for the use case when you have variants with different combinations of mutations than those found in the training set.

This could mirror the functionality of https://jbloomlab.github.io/dms_variants/dms_variants.globalepistasis.html#dms_variants.globalepistasis.AbstractEpistasis.add_phenotypes_to_df

**Comment by jgallowa07** [comment]
@jbloom I notices that function from dms_variants only has two options for dealing with mutations which are unknown to the model. Either throw and error if any of the variants contain them, or predict nan. Would it be helpful to have an option for a "partial prediction" by just tossing unknown mutations from the genotype (substitutions string) - effectively treating the unknown mutation effect as 0?

**Comment by jbloom** [comment]
No, I think this is bad, because the "average" mutation does not have an effect of zero. I think we should just stick with throwing an error or returning `NaN`---we never want predictions for mutations w no data.
