### ISSUE TITLE
is it a good idea to have data frame columns with Greek character str names?

### ISSUE THREAD

**Issue by jbloom** [matsengrp/multidms#74]
Some columns have names that don't use standard alphanumeric characters. For instance, `Model.mutations_df` returns a column with the name `"β"`. Is this a good idea, or is it better to have columns named using standard alphanumeric characters? I'm not even sure how to type "β" on my computer keyboard!

**Comment by jgallowa07** [comment]
I agree this is weird. Thought it was originally nice just for reading the math and code side by side ... but I fully agree, I'll change this.

**Comment by jgallowa07** [comment]
I'm changing internal variables to achieve

1. from greek -> ascii 
2. ^ which in turn, will change to the reported column names. 
3. sync up with the changes to the manuscript 
 
Here's  list of variable changes that will be made globally:

- [ ] α -> theta # note that we are now using alpha as a constant term in the latent model
- [ ] δ -> huber_scale
- [ ] λ -> scale
- [ ] β -> beta
- [ ] C_ref -> beta_naught
- [ ] C_ -> alpha_
- [ ] γ -> gamma
- [ ] S_ -> shift_

**Comment by jgallowa07** [comment]
#81 Finished this
