### ISSUE TITLE
missing logo in docs

### ISSUE THREAD

**Issue by WSDeWitt** [matsengrp/multidms#77]
In docs, the upper-right link to GitHub seems to be missing a logo file.

![image](https://github.com/matsengrp/multidms/assets/1173298/c1d9bf5c-7989-49b5-afc1-131479bdfaca)

**Comment by jgallowa07** [comment]
Couldn't figure out how to point to a new image immediately, so I just remove it here in [7f55744c](https://github.com/matsengrp/multidms/commit/7f55744c7a093c490143a3639263cb01712c13aa) Closing for now, thanks!
