### ISSUE TITLE
minor suggestions on biophysical model docs page

### ISSUE THREAD

**Issue by WSDeWitt** [matsengrp/multidms#78]
- 1st paragraph: drop quotes on $L_1$, maybe put lasso in parenthesis, and cite the lasso book.
- Citations could be done in the usual sphinx fashion, so they appear as endnotes.
- The heading "Joint-model composition" could drop the hyphen
- In the last sentence of the 2nd paragraph, I suggest referring to the mutational effects vector $\beta$ and shift matrix $\Delta$, rather than the arbitrary entries $\beta_m$ and $\Delta_{d,m}$ (you have not defined the indices $d$ or $m$, and anyway you are inferring the entire vector and matrix).
- Change nonlinear parameters $\alpha$ to $\theta$ to match main text.
- The paragraph beginning "**Note** The motivation behind..." would be fine without the bold **Note**.
- I suggest changing $d\in\\{d_1, d_2, d_3\\}$ to $d\in\\{1,2,3\\}$, since these concretely are integer indices into vectors and matrices. Then you can define $d=1$ for the reference condition in the example, and you avoid all the nested subscripting like $\Delta_{d_2,m}$.
- I see a remnant of the old notation $s$ for the shift matrix, which I think should be $\Delta$.
- I didn't know "coherency" is a word (I checked, it is). I don't know if having the reference experiment shifts "exist" is mathematically coherent per se—I would just say that, for convenient indexing and array operations, we store a matrix of shifts for all experiments but fix the reference experiment's row to be zeros.
- For some reason, I don't like the "Importantly...", but that's a matter of taste.
- $C_d$ is discussed but not defined (possibly outdated notation).
- The phrase _latent phenotype_ is repeatedly italicized. It's probably only meant to be the first time?
- Interactive plots are nice! Do you want one for softplus?
- The matrix $E$ is referenced but not defined in the discussion of enrichment ratios.
- The notation in the "Fitting procedure" section should be updated to better match the methods section text on this. Generally, it would be preferable to see the parameters you optimize appear as arguments of the objective function.
- The paragraph beginning "To get ready for future more general non-smooth penalties...": I don't know what this is talking about because you're already using a non-smooth penalty here. Maybe this is text from an outdated version?

**Comment by jgallowa07** [comment]
These were addressed in https://github.com/matsengrp/multidms/commit/18a7fcd2fcfe18ccc46a8f5d513331cb49c1ced1.

Thanks, @WSDeWitt ! I think that really cleaned things up :)
