### ISSUE TITLE
Naming and docs improvements

### ISSUE THREAD

**Issue by WSDeWitt** [matsengrp/multidms#82]
Repetitious names
--

The current names result in unnecessarily redundant text in API calls, for example:
```python
import multidms

data = multidms.MultiDmsData(...)
model = multidms.MultiDmsModel(...)
```
I don't see any need to have the phrase "multidms" appearing twice in a row. It would be like having
```python
import pandas

df = pandas.PandasDataFrame(...)
```
I recommend shortening the class names to `Data` and `Model`, which would result in tidier code like this:
```python
import multidms

data = multidms.Data(...)
model = multidms.Model(...)
```

Insufficient docstrings
--

The documentation for `data` and `model` modules is great, but the `biophysical` module docs are superficial and vague. None of the docstrings provide parameter documentation, so one needs to dig into the source code to deduce how to use these.

Public Vs private
--

I'm not sure if the `abstract_...` functions are intended to be exposed in the API. If so, I think they need more documentation to explain how to use them. If not, they should be private members (prefixed with an underscore) that don't appear in the docs.

Other possible restructuring
--

- There are several function names with the suffix `_global_epistasis`, which indicates to me that these should instead live in a module file called `global_epistasis`, with the suffix dropped.
- There are some functions ending with the suffix `_activation`, but it's not made clear what these are for.

**Comment by jgallowa07** [comment]
This was addressed in #85. Closing for now.
