### ISSUE TITLE
"func_score" -> "phenotype" nomenclature

### ISSUE THREAD

**Issue by jgallowa07** [matsengrp/multidms#89]
@jbloom  Based on the historical "func_scores_df" dataframe from binarymap, the code has references everywhere to `func_score` and "functional score". Should these be globally replaced with phenotype? Is there a difference?

**Comment by jbloom** [comment]
I think "functional score" is fine. 

Originally I was using the nomenclature where the "functional score" is also called the "observed phenotype", and then there is the "latent phenotype."

I think it is fine if we also just use "functional score" and "latent phenotype", which is what I think you do now.
