### ISSUE TITLE
revise CONTRIBUTING

### ISSUE THREAD

**Issue by WSDeWitt** [matsengrp/multidms#98]
There are some copypasta references to `test_requirements.txt` that need revision.

**Comment by WSDeWitt** [comment]
For dev docs, we should mention the pandoc dependency. E.g.
```
conda install -c conda-forge pandoc
```

**Comment by WSDeWitt** [comment]
There are several dead links to nonexistent repo files:
- ruff config
- pytest config
- Docs readme

**Comment by jgallowa07** [comment]
This should have closed with #105
